name: Deploy Scheduler Service
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:${{ github.sha }}
    
    - name: Initialize Swarm if needed
      run: |
        if ! docker info | grep -q "Swarm: active"; then
          docker swarm init
        fi

    - name: Create or update network if needed
      run: |
        if ! docker network ls | grep -q "swecc-network"; then
          docker network create --driver overlay --attachable swecc-network
        fi

    - name: Deploy scheduler service
      run: |
        # Remove the existing service if it exists
        docker service rm scheduler || true
        
        # Create the service with environment variables
        docker service create \
          --name scheduler \
          --network swecc-network \
          --config scheduler_env\
          --replicas 1 \
          --restart-condition any \
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest