name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:${{ github.sha }}
    
    - name: Deploy scheduler
      run: |
        docker stop scheduler || true
        docker rm scheduler || true
        
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest
        
        docker run -d --name scheduler \
          --network swag-network \
          -e ENV=prod  \
          -e SCHEDULER_API_KEY=${{ secrets.SCHEDULER_API_KEY }} \
          --restart unless-stopped \
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest
