name: Deploy Scheduler Service
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:${{ github.sha }}

    - name: Deploy scheduler service
      run: |
        # Remove the existing service if it exists
        docker service rm scheduler || true
        
        # Extract environment variables from config
        docker config inspect scheduler_env --pretty | sed -n '/Data:/,$ p' | sed '1d' > env_file.txt

        # Deploy the service with the env file
        docker service create \
          --name scheduler \
          --network swecc-network \
          --env-file env_file.txt \
          --replicas 1 \
          --restart-condition any \
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-scheduler:latest

        # Clean up
        rm env_file.txt